import { Document, Page, Text, View, Image, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { formatMoneyPlain } from "@/lib/crm/currency";
import type {
  ClientsReportData,
  LeadsReportData,
  InvoicesReportData,
  ExecutiveReportData,
} from "./data";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, fontFamily: "Helvetica", color: "#111827", backgroundColor: "#ffffff" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20, paddingBottom: 12, borderBottomWidth: 1.5, borderColor: "#e5e7eb" },
  brandBlock: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 44, height: 44, objectFit: "contain" },
  companyName: { fontSize: 13, fontWeight: 700, color: "#111827" },
  reportTitle: { fontSize: 18, fontWeight: 700, color: "#111827", textAlign: "right" },
  reportPeriod: { fontSize: 10, color: "#6b7280", marginTop: 2, textAlign: "right" },
  
  // KPI summary block
  kpiContainer: { flexDirection: "row", gap: 8, marginBottom: 18 },
  kpiCard: { flex: 1, backgroundColor: "#f9fafb", borderWidth: 1, borderColor: "#e5e7eb", borderRadius: 6, padding: 8 },
  kpiLabel: { fontSize: 7.5, color: "#6b7280", textTransform: "uppercase", fontWeight: 700, marginBottom: 3 },
  kpiValue: { fontSize: 13, fontWeight: 700, color: "#111827" },
  kpiSub: { fontSize: 7.5, color: "#9ca3af", marginTop: 2 },

  // Table styles
  sectionTitle: { fontSize: 11, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 10 },
  table: { borderWidth: 1, borderColor: "#e5e7eb", borderRadius: 6, overflow: "hidden", marginBottom: 14 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f3f4f6", borderBottomWidth: 1, borderColor: "#e5e7eb", paddingVertical: 5, paddingHorizontal: 6, fontWeight: 700, fontSize: 8 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#f3f4f6", paddingVertical: 5, paddingHorizontal: 6, alignItems: "center" },
  tableRowAlt: { backgroundColor: "#fafafa" },

  // Badges
  badgeNew: { backgroundColor: "#dbeafe", color: "#1d4ed8", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },
  badgeBf: { backgroundColor: "#f3f4f6", color: "#4b5563", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },
  badgeWon: { backgroundColor: "#dcfce7", color: "#15803d", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },
  badgeLost: { backgroundColor: "#fee2e2", color: "#b91c1c", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },
  badgeOpen: { backgroundColor: "#e0f2fe", color: "#0369a1", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },
  badgeCritical: { backgroundColor: "#fee2e2", color: "#b91c1c", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },
  badgeWarning: { backgroundColor: "#fef3c7", color: "#b45309", paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 4, fontSize: 7, fontWeight: 700 },

  footer: { position: "absolute", bottom: 20, left: 36, right: 36, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#9ca3af", borderTopWidth: 1, borderColor: "#f3f4f6", paddingTop: 8 },
});

function Header({ title, period, data }: { title: string; period: string; data: ClientsReportData | LeadsReportData | InvoicesReportData | ExecutiveReportData }) {
  const brandColor = data.settings?.brand_color || "#3b82f6";
  return (
    <View style={styles.header}>
      <View style={styles.brandBlock}>
        {data.settings?.logo_url && <Image src={data.settings.logo_url} style={styles.logo} />}
        <View>
          <Text style={[styles.companyName, { color: brandColor }]}>{data.settings?.business_name || "CRM Portal"}</Text>
          {data.settings?.business_email && <Text style={{ fontSize: 8, color: "#6b7280" }}>{data.settings.business_email}</Text>}
        </View>
      </View>
      <View>
        <Text style={styles.reportTitle}>{title}</Text>
        <Text style={styles.reportPeriod}>{period}</Text>
      </View>
    </View>
  );
}

function Footer({ pageStr = "Page 1" }: { pageStr?: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text>Confidential · Generated by CRM Executive Engine</Text>
      <Text>{pageStr}</Text>
    </View>
  );
}

// -------------------------------------------------------------
// 1. Clients Report PDF
// -------------------------------------------------------------
export async function renderClientsPdf(data: ClientsReportData): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Header title="CLIENTS DIRECTORY REPORT" period={data.range.label} data={data} />

        {/* KPI Scorecards */}
        <View style={styles.kpiContainer}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Total Active Clients</Text>
            <Text style={styles.kpiValue}>{data.summary.totalClients}</Text>
            <Text style={styles.kpiSub}>{data.summary.newClientsCount} new · {data.summary.broughtForwardCount} brought fwd</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Total Invoiced</Text>
            <Text style={styles.kpiValue}>{formatMoneyPlain(data.summary.totalBilled, data.summary.currency)}</Text>
            <Text style={styles.kpiSub}>Lifetime up to period</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Cash Collected</Text>
            <Text style={[styles.kpiValue, { color: "#16a34a" }]}>{formatMoneyPlain(data.summary.totalPaid, data.summary.currency)}</Text>
            <Text style={styles.kpiSub}>Settled in full / part</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Outstanding Receivables</Text>
            <Text style={[styles.kpiValue, { color: data.summary.totalOutstanding > 0 ? "#dc2626" : "#111827" }]}>
              {formatMoneyPlain(data.summary.totalOutstanding, data.summary.currency)}
            </Text>
            <Text style={styles.kpiSub}>Unpaid client balance</Text>
          </View>
        </View>

        {/* Detailed Client Table */}
        <Text style={styles.sectionTitle}>Client Accounts & Financial Position</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 3 }}>Client & Company</Text>
            <Text style={{ flex: 1.5 }}>Status</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Invoiced</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Paid</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Balance Due</Text>
          </View>
          {data.clients.map((c, idx) => (
            <View key={c.id} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]} wrap={false}>
              <View style={{ flex: 3 }}>
                <Text style={{ fontWeight: 700, color: "#111827" }}>{c.name}</Text>
                <Text style={{ fontSize: 7.5, color: "#6b7280" }}>{c.company || c.email || "No company"}</Text>
              </View>
              <View style={{ flex: 1.5 }}>
                {c.classification === "new" ? (
                  <Text style={styles.badgeNew}>NEW CLIENT</Text>
                ) : (
                  <Text style={styles.badgeBf}>BROUGHT FWD</Text>
                )}
              </View>
              <Text style={{ flex: 1.5, textAlign: "right", color: "#374151" }}>
                {formatMoneyPlain(c.totalBilled, c.currency)}
              </Text>
              <Text style={{ flex: 1.5, textAlign: "right", color: "#16a34a" }}>
                {formatMoneyPlain(c.totalPaid, c.currency)}
              </Text>
              <Text style={{ flex: 1.5, textAlign: "right", fontWeight: 700, color: c.balance > 0 ? "#dc2626" : "#374151" }}>
                {formatMoneyPlain(c.balance, c.currency)}
              </Text>
            </View>
          ))}
        </View>

        <Footer />
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}

// -------------------------------------------------------------
// 2. Leads Report PDF
// -------------------------------------------------------------
export async function renderLeadsPdf(data: LeadsReportData): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Header title="SALES LEADS & PIPELINE REPORT" period={data.range.label} data={data} />

        {/* KPI Scorecards */}
        <View style={styles.kpiContainer}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Total Leads</Text>
            <Text style={styles.kpiValue}>{data.summary.totalLeads}</Text>
            <Text style={styles.kpiSub}>{data.summary.newLeadsCount} new · {data.summary.carriedOverCount} carried fwd</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Won Deals</Text>
            <Text style={[styles.kpiValue, { color: "#16a34a" }]}>{data.summary.wonCount}</Text>
            <Text style={styles.kpiSub}>Win rate: {data.summary.winRate}%</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Active Open Pipeline</Text>
            <Text style={[styles.kpiValue, { color: "#0284c7" }]}>{data.summary.openCount}</Text>
            <Text style={styles.kpiSub}>In negotiation / pitch</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Stalled Inactivity (&gt;21d)</Text>
            <Text style={[styles.kpiValue, { color: data.summary.stalledCount > 0 ? "#dc2626" : "#111827" }]}>
              {data.summary.stalledCount}
            </Text>
            <Text style={styles.kpiSub}>Needs immediate outreach</Text>
          </View>
        </View>

        {/* Leads Table */}
        <Text style={styles.sectionTitle}>Pipeline Stage Progression & Health</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 3 }}>Lead & Organization</Text>
            <Text style={{ flex: 1.5 }}>Cohort</Text>
            <Text style={{ flex: 2 }}>Current Stage</Text>
            <Text style={{ flex: 1.2 }}>Status</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Health</Text>
          </View>
          {data.leads.map((l, idx) => (
            <View key={l.id} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]} wrap={false}>
              <View style={{ flex: 3 }}>
                <Text style={{ fontWeight: 700, color: "#111827" }}>{l.name}</Text>
                <Text style={{ fontSize: 7.5, color: "#6b7280" }}>{l.company || l.email || "Individual"}</Text>
              </View>
              <View style={{ flex: 1.5 }}>
                {l.classification === "new" ? (
                  <Text style={styles.badgeNew}>NEW LEAD</Text>
                ) : (
                  <Text style={styles.badgeBf}>CARRIED OVER</Text>
                )}
              </View>
              <Text style={{ flex: 2, color: "#374151" }}>{l.current_stage_label}</Text>
              <View style={{ flex: 1.2 }}>
                {l.status === "won" ? (
                  <Text style={styles.badgeWon}>WON</Text>
                ) : l.status === "lost" ? (
                  <Text style={styles.badgeLost}>LOST</Text>
                ) : (
                  <Text style={styles.badgeOpen}>OPEN</Text>
                )}
              </View>
              <View style={{ flex: 1.5, alignItems: "flex-end" }}>
                {l.isStalled ? (
                  <Text style={styles.badgeCritical}>STALLED ({l.daysSinceLastActivity}d)</Text>
                ) : (
                  <Text style={{ fontSize: 7.5, color: "#6b7280" }}>Active ({l.daysSinceLastActivity}d)</Text>
                )}
              </View>
            </View>
          ))}
        </View>

        <Footer />
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}

// -------------------------------------------------------------
// 3. Invoices Report PDF
// -------------------------------------------------------------
export async function renderInvoicesPdf(data: InvoicesReportData): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Header title="INVOICES & FINANCIAL RECEIVABLES" period={data.range.label} data={data} />

        {/* KPI Scorecards */}
        <View style={styles.kpiContainer}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Gross Invoiced</Text>
            <Text style={styles.kpiValue}>{formatMoneyPlain(data.summary.grossInvoiced, data.summary.currency)}</Text>
            <Text style={styles.kpiSub}>{data.summary.totalInvoices} invoices in period</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Net Cash Collected</Text>
            <Text style={[styles.kpiValue, { color: "#16a34a" }]}>{formatMoneyPlain(data.summary.netCollected, data.summary.currency)}</Text>
            <Text style={styles.kpiSub}>Recorded payment total</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Total Receivables</Text>
            <Text style={[styles.kpiValue, { color: data.summary.totalOutstanding > 0 ? "#dc2626" : "#111827" }]}>
              {formatMoneyPlain(data.summary.totalOutstanding, data.summary.currency)}
            </Text>
            <Text style={styles.kpiSub}>Unpaid invoice balance</Text>
          </View>
        </View>

        {/* Aging Buckets Table */}
        <Text style={styles.sectionTitle}>Receivables Aging Analysis</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 3 }}>Aging Category</Text>
            <Text style={{ flex: 2 }}>Criteria</Text>
            <Text style={{ flex: 1.5, textAlign: "center" }}>Count</Text>
            <Text style={{ flex: 2.5, textAlign: "right" }}>Outstanding Balance</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={{ flex: 3, fontWeight: 700 }}>Current Receivables</Text>
            <Text style={{ flex: 2, color: "#6b7280" }}>0 – 30 days due</Text>
            <Text style={{ flex: 1.5, textAlign: "center" }}>{data.summary.agingCurrent.count}</Text>
            <Text style={{ flex: 2.5, textAlign: "right", fontWeight: 700 }}>
              {formatMoneyPlain(data.summary.agingCurrent.amount, data.summary.currency)}
            </Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={{ flex: 3, fontWeight: 700, color: "#b45309" }}>Overdue (Warning)</Text>
            <Text style={{ flex: 2, color: "#6b7280" }}>31 – 60 days past due</Text>
            <Text style={{ flex: 1.5, textAlign: "center" }}>{data.summary.agingOverdue30.count}</Text>
            <Text style={{ flex: 2.5, textAlign: "right", fontWeight: 700, color: "#b45309" }}>
              {formatMoneyPlain(data.summary.agingOverdue30.amount, data.summary.currency)}
            </Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={{ flex: 3, fontWeight: 700, color: "#dc2626" }}>Critical Delinquent</Text>
            <Text style={{ flex: 2, color: "#6b7280" }}>&gt; 60 days past due</Text>
            <Text style={{ flex: 1.5, textAlign: "center" }}>{data.summary.agingCritical60.count}</Text>
            <Text style={{ flex: 2.5, textAlign: "right", fontWeight: 700, color: "#dc2626" }}>
              {formatMoneyPlain(data.summary.agingCritical60.amount, data.summary.currency)}
            </Text>
          </View>
        </View>

        {/* Invoice Item List */}
        <Text style={styles.sectionTitle}>Invoices Breakdown</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 2 }}>Number</Text>
            <Text style={{ flex: 3 }}>Client</Text>
            <Text style={{ flex: 1.5 }}>Due Date</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Total</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Balance Due</Text>
            <Text style={{ flex: 1.5, textAlign: "right" }}>Aging</Text>
          </View>
          {data.invoices.map((inv, idx) => (
            <View key={inv.id} style={[styles.tableRow, idx % 2 === 1 ? styles.tableRowAlt : {}]} wrap={false}>
              <Text style={{ flex: 2, fontWeight: 700 }}>{inv.number}</Text>
              <View style={{ flex: 3 }}>
                <Text style={{ fontWeight: 700 }}>{inv.clientName}</Text>
                <Text style={{ fontSize: 7, color: "#6b7280" }}>{inv.clientCompany || "—"}</Text>
              </View>
              <Text style={{ flex: 1.5, fontSize: 8, color: "#6b7280" }}>{inv.effectiveDueDate}</Text>
              <Text style={{ flex: 1.5, textAlign: "right" }}>{formatMoneyPlain(inv.total, inv.currency)}</Text>
              <Text style={{ flex: 1.5, textAlign: "right", fontWeight: 700, color: inv.balance > 0 ? "#dc2626" : "#16a34a" }}>
                {formatMoneyPlain(inv.balance, inv.currency)}
              </Text>
              <View style={{ flex: 1.5, alignItems: "flex-end" }}>
                {inv.agingBucket === "critical_60" ? (
                  <Text style={styles.badgeCritical}>&gt;60D</Text>
                ) : inv.agingBucket === "overdue_30" ? (
                  <Text style={styles.badgeWarning}>30-60D</Text>
                ) : (
                  <Text style={{ fontSize: 7, color: "#16a34a" }}>CURRENT</Text>
                )}
              </View>
            </View>
          ))}
        </View>

        <Footer />
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}

// -------------------------------------------------------------
// 4. Executive ("ALL") Report PDF
// -------------------------------------------------------------
export async function renderExecutivePdf(data: ExecutiveReportData): Promise<Buffer> {
  const doc = (
    <Document>
      {/* Page 1: Executive KPI Overview */}
      <Page size="A4" style={styles.page}>
        <Header title="EXECUTIVE CRM PERFORMANCE REPORT" period={data.range.label} data={data} />

        <View style={styles.kpiContainer}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Revenue Billed</Text>
            <Text style={styles.kpiValue}>{formatMoneyPlain(data.invoicesSummary.grossInvoiced, data.invoicesSummary.currency)}</Text>
            <Text style={styles.kpiSub}>Invoiced in period</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Cash Inflow</Text>
            <Text style={[styles.kpiValue, { color: "#16a34a" }]}>{formatMoneyPlain(data.invoicesSummary.netCollected, data.invoicesSummary.currency)}</Text>
            <Text style={styles.kpiSub}>Actual cash collected</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Unpaid Receivables</Text>
            <Text style={[styles.kpiValue, { color: data.invoicesSummary.totalOutstanding > 0 ? "#dc2626" : "#111827" }]}>
              {formatMoneyPlain(data.invoicesSummary.totalOutstanding, data.invoicesSummary.currency)}
            </Text>
            <Text style={styles.kpiSub}>Outstanding balances</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Pipeline Win Rate</Text>
            <Text style={[styles.kpiValue, { color: "#0284c7" }]}>{data.leadsSummary.winRate}%</Text>
            <Text style={styles.kpiSub}>{data.leadsSummary.wonCount} won · {data.leadsSummary.openCount} in play</Text>
          </View>
        </View>

        {/* Section: Receivables Aging */}
        <Text style={styles.sectionTitle}>1. Cash Flow & Receivables Aging</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 3 }}>Aging Window</Text>
            <Text style={{ flex: 2, textAlign: "center" }}>Invoices Count</Text>
            <Text style={{ flex: 3, textAlign: "right" }}>Outstanding Balance</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={{ flex: 3 }}>Current (0–30 Days)</Text>
            <Text style={{ flex: 2, textAlign: "center" }}>{data.invoicesSummary.agingCurrent.count}</Text>
            <Text style={{ flex: 3, textAlign: "right", fontWeight: 700 }}>
              {formatMoneyPlain(data.invoicesSummary.agingCurrent.amount, data.invoicesSummary.currency)}
            </Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={{ flex: 3, color: "#b45309", fontWeight: 700 }}>Overdue (31–60 Days)</Text>
            <Text style={{ flex: 2, textAlign: "center" }}>{data.invoicesSummary.agingOverdue30.count}</Text>
            <Text style={{ flex: 3, textAlign: "right", color: "#b45309", fontWeight: 700 }}>
              {formatMoneyPlain(data.invoicesSummary.agingOverdue30.amount, data.invoicesSummary.currency)}
            </Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={{ flex: 3, color: "#dc2626", fontWeight: 700 }}>Critical Delinquent (&gt;60 Days)</Text>
            <Text style={{ flex: 2, textAlign: "center" }}>{data.invoicesSummary.agingCritical60.count}</Text>
            <Text style={{ flex: 3, textAlign: "right", color: "#dc2626", fontWeight: 700 }}>
              {formatMoneyPlain(data.invoicesSummary.agingCritical60.amount, data.invoicesSummary.currency)}
            </Text>
          </View>
        </View>

        {/* Top Delinquent Accounts */}
        <Text style={styles.sectionTitle}>2. Top Unpaid Invoices Requiring Follow-Up</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={{ flex: 2 }}>Invoice</Text>
            <Text style={{ flex: 3 }}>Client</Text>
            <Text style={{ flex: 2 }}>Due Date</Text>
            <Text style={{ flex: 2, textAlign: "right" }}>Balance Due</Text>
          </View>
          {data.topDebtors.slice(0, 5).map((d) => (
            <View key={d.id} style={styles.tableRow}>
              <Text style={{ flex: 2, fontWeight: 700 }}>{d.number}</Text>
              <Text style={{ flex: 3 }}>{d.clientName}</Text>
              <Text style={{ flex: 2, color: "#6b7280" }}>{d.effectiveDueDate}</Text>
              <Text style={{ flex: 2, textAlign: "right", fontWeight: 700, color: "#dc2626" }}>
                {formatMoneyPlain(d.balance, d.currency)}
              </Text>
            </View>
          ))}
        </View>

        {/* Stalled Leads Alerts */}
        {data.stalledLeads.length > 0 && (
          <>
            <Text style={[styles.sectionTitle, { color: "#b45309" }]}>3. Stalled Deal Pipeline (No Activity &gt;21 Days)</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={{ flex: 3 }}>Prospect</Text>
                <Text style={{ flex: 2.5 }}>Current Stage</Text>
                <Text style={{ flex: 2.5, textAlign: "right" }}>Days Idle</Text>
              </View>
              {data.stalledLeads.slice(0, 4).map((sl) => (
                <View key={sl.id} style={styles.tableRow}>
                  <Text style={{ flex: 3, fontWeight: 700 }}>{sl.name} ({sl.company || "Individual"})</Text>
                  <Text style={{ flex: 2.5, color: "#6b7280" }}>{sl.current_stage_label}</Text>
                  <Text style={{ flex: 2.5, textAlign: "right", color: "#b45309", fontWeight: 700 }}>{sl.daysSinceLastActivity} days inactive</Text>
                </View>
              ))}
            </View>
          </>
        )}

        <Footer pageStr="Page 1 of 1" />
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}
